### ISSUE TITLE
New build?

### ISSUE THREAD

**Issue by shammahatdivvy** [JetBrains/teamcity-github-auth#11]
Github deprecated their old token format, and all logins are failing now for anyone using this plugin unless they compile a custom version. There's no build instructions in this repository to do so. It would be nice if someone could fire off a build so users can get a new plugin version.

**Comment by dmitry-treskunov** [comment]
Hi, could you please provide more details about how all logins are failing?

**Comment by shammahatdivvy** [comment]
Yes:

```
Unexpected Error
This was not supposed to happen. Please provide the error details to your TeamCity server maintainer.
If you maintain this TeamCity installation and the request seems legit please report this error to JetBrains.

Error: org.jetbrains.teamcity.githubauth.GitHubLoginException: Error obtaining GitHub user

Server time: 2021-09-22 21:45:49
TeamCity: 2021.1.3 (build 92914)
Servlet container: Apache Tomcat/8.5.65

Trace: org.jetbrains.teamcity.githubauth.GitHubLoginException: Error obtaining GitHub user
	at org.jetbrains.teamcity.githubauth.GitHubOAuthClient.getUser(GitHubOAuthClient.java:55)
	at org.jetbrains.teamcity.githubauth.GitHubOAuth.processAuthenticationRequest(GitHubOAuth.java:91)
	at jetbrains.buildServer.controllers.interceptors.auth.impl.HttpAuthenticationManagerImpl.lambda$doProcessAuthenticationRequest$0(HttpAuthenticationManagerImpl.java:108)
	at jetbrains.buildServer.serverSide.impl.BaseAccessChecker.runWithDisabledChecks(BaseAccessChecker.java:21)
	at jetbrains.buildServer.serverSide.impl.SecondaryNodeSecurityManager.executeSafe(SecondaryNodeSecurityManager.java:28)
	at jetbrains.buildServer.serverSide.IOGuardInitializer$IOGuardDelegateImpl.allowNetworkCall(IOGuardInitializer.java:2)
	at jetbrains.buildServer.serverSide.IOGuard.allowNetworkCall(IOGuard.java:82)

....
```

Fairly certain it was fixed with this PR: https://github.com/JetBrains/teamcity-github-auth/pull/10

**Comment by dmitry-treskunov** [comment]
Oh, sorry, so please take this build, it should work https://teamcity.jetbrains.com/buildConfiguration/TeamCityPluginsByJetBrains_TeamCityGitHubAuthentication_Build/3627187?buildTab=artifacts

**Comment by shammahatdivvy** [comment]
Seems to work. Thank you!
